### ISSUE TITLE
Не загружается главная страница с начала при нажатии иконки SKYRENT в футере

### ISSUE THREAD

**Issue by SlyusNat** [Diableros/RAID2Front#2]
1. Зайти на сайт
2. Подобрать жилье по интересующим параметрам
3. Пролистать список вниз
4. Нажать иконку SKYRENT в футере

ОР: сайт возвращается на главную страницу
ФР: прогружаются все варианты жилья (кроме подобранного), но остается на последнем выбранном варианте

**Comment by Diableros** [comment]
Вроде починил. Жду подтверждения.
